#!/bin/bash

# Uncomment the following two lines for normal desktop:
#unset SESSION_MANAGER
#exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
[ -r $HOME/.bash_profile ] && . $HOME/.bash_profile

[ -x /usr/bin/dbus-launch ] && eval $(dbus-launch --sh-syntax --exit-with-session)
[ -x /usr/bin/gnome-keyring-daemon ] && eval $(cat ~/.install-secret | gnome-keyring-daemon --daemonize --unlock)
[ -x /usr/bin/urxvtd ] && (urxvtd -q -f -o ; export TERMINAL=urxvtc)

xsetroot -solid grey
x-terminal-emulator &

exec i3
